package com.javaweb.model;
// Generated Dec 20, 2016 11:01:57 PM by Hibernate Tools 4.3.1



/**
 * Baocao generated by hbm2java
 */
public class Baocao  implements java.io.Serializable {


     private Integer idbaocao;
     private int idtaikhoan;
     private String noiDung;
     private String ghiChu;

    public Baocao() {
    }

	
    public Baocao(int idtaikhoan, String noiDung) {
        this.idtaikhoan = idtaikhoan;
        this.noiDung = noiDung;
    }
    public Baocao(int idtaikhoan, String noiDung, String ghiChu) {
       this.idtaikhoan = idtaikhoan;
       this.noiDung = noiDung;
       this.ghiChu = ghiChu;
    }
   
    public Integer getIdbaocao() {
        return this.idbaocao;
    }
    
    public void setIdbaocao(Integer idbaocao) {
        this.idbaocao = idbaocao;
    }
    public int getIdtaikhoan() {
        return this.idtaikhoan;
    }
    
    public void setIdtaikhoan(int idtaikhoan) {
        this.idtaikhoan = idtaikhoan;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }




}


