package com.javaweb.model;
// Generated Dec 3, 2016 1:09:20 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Chuyenbay generated by hbm2java
 */
public class Chuyenbay  implements java.io.Serializable {


     private Integer idchuyenbay;
     private String chuyenBay;
     private Date thoiGian;
     private int idloaichuyenbay;

    public Chuyenbay() {
    }

    public Chuyenbay(String chuyenBay, Date thoiGian, int idloaichuyenbay) {
       this.chuyenBay = chuyenBay;
       this.thoiGian = thoiGian;
       this.idloaichuyenbay = idloaichuyenbay;
    }
   
    public Integer getIdchuyenbay() {
        return this.idchuyenbay;
    }
    
    public void setIdchuyenbay(Integer idchuyenbay) {
        this.idchuyenbay = idchuyenbay;
    }
    public String getChuyenBay() {
        return this.chuyenBay;
    }
    
    public void setChuyenBay(String chuyenBay) {
        this.chuyenBay = chuyenBay;
    }
    public Date getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }
    public int getIdloaichuyenbay() {
        return this.idloaichuyenbay;
    }
    
    public void setIdloaichuyenbay(int idloaichuyenbay) {
        this.idloaichuyenbay = idloaichuyenbay;
    }




}


