package com.javaweb.model;
// Generated Dec 12, 2016 2:00:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Chuyenbay generated by hbm2java
 */
public class Chuyenbay  implements java.io.Serializable {


     private Integer idchuyenbay;
     private String tu;
     private String den;
     private Date ngayKhoiHanh;
     private Date gioCatCanh;
     private Date gioHaCanh;
     private String loaiMayBay;
     private BigDecimal giaChuyenBay;

    public Chuyenbay() {
    }

    public Chuyenbay(String tu, String den, Date ngayKhoiHanh, Date gioCatCanh, Date gioHaCanh, String loaiMayBay, BigDecimal giaChuyenBay) {
       this.tu = tu;
       this.den = den;
       this.ngayKhoiHanh = ngayKhoiHanh;
       this.gioCatCanh = gioCatCanh;
       this.gioHaCanh = gioHaCanh;
       this.loaiMayBay = loaiMayBay;
       this.giaChuyenBay = giaChuyenBay;
    }
   
    public Integer getIdchuyenbay() {
        return this.idchuyenbay;
    }
    
    public void setIdchuyenbay(Integer idchuyenbay) {
        this.idchuyenbay = idchuyenbay;
    }
    public String getTu() {
        return this.tu;
    }
    
    public void setTu(String tu) {
        this.tu = tu;
    }
    public String getDen() {
        return this.den;
    }
    
    public void setDen(String den) {
        this.den = den;
    }
    public Date getNgayKhoiHanh() {
        return this.ngayKhoiHanh;
    }
    
    public void setNgayKhoiHanh(Date ngayKhoiHanh) {
        this.ngayKhoiHanh = ngayKhoiHanh;
    }
    public Date getGioCatCanh() {
        return this.gioCatCanh;
    }
    
    public void setGioCatCanh(Date gioCatCanh) {
        this.gioCatCanh = gioCatCanh;
    }
    public Date getGioHaCanh() {
        return this.gioHaCanh;
    }
    
    public void setGioHaCanh(Date gioHaCanh) {
        this.gioHaCanh = gioHaCanh;
    }
    public String getLoaiMayBay() {
        return this.loaiMayBay;
    }
    
    public void setLoaiMayBay(String loaiMayBay) {
        this.loaiMayBay = loaiMayBay;
    }
    public BigDecimal getGiaChuyenBay() {
        return this.giaChuyenBay;
    }
    
    public void setGiaChuyenBay(BigDecimal giaChuyenBay) {
        this.giaChuyenBay = giaChuyenBay;
    }




}


