package com.javaweb.model;
// Generated Dec 15, 2016 5:22:22 PM by Hibernate Tools 4.3.1



/**
 * Loaitaikhoan generated by hbm2java
 */
public class Loaitaikhoan  implements java.io.Serializable {


     private Integer idloaitaikhoan;
     private String loaiTk;
     private String moTa;

    public Loaitaikhoan() {
    }

	
    public Loaitaikhoan(String loaiTk) {
        this.loaiTk = loaiTk;
    }
    public Loaitaikhoan(String loaiTk, String moTa) {
       this.loaiTk = loaiTk;
       this.moTa = moTa;
    }
   
    public Integer getIdloaitaikhoan() {
        return this.idloaitaikhoan;
    }
    
    public void setIdloaitaikhoan(Integer idloaitaikhoan) {
        this.idloaitaikhoan = idloaitaikhoan;
    }
    public String getLoaiTk() {
        return this.loaiTk;
    }
    
    public void setLoaiTk(String loaiTk) {
        this.loaiTk = loaiTk;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }




}


