package com.javaweb.model;
// Generated Dec 15, 2016 5:22:22 PM by Hibernate Tools 4.3.1



/**
 * Loaive generated by hbm2java
 */
public class Loaive  implements java.io.Serializable {


     private Integer idloaive;
     private String loaiVe;
     private String moTa;

    public Loaive() {
    }

	
    public Loaive(String loaiVe) {
        this.loaiVe = loaiVe;
    }
    public Loaive(String loaiVe, String moTa) {
       this.loaiVe = loaiVe;
       this.moTa = moTa;
    }
   
    public Integer getIdloaive() {
        return this.idloaive;
    }
    
    public void setIdloaive(Integer idloaive) {
        this.idloaive = idloaive;
    }
    public String getLoaiVe() {
        return this.loaiVe;
    }
    
    public void setLoaiVe(String loaiVe) {
        this.loaiVe = loaiVe;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }




}


