package com.javaweb.model;
// Generated Dec 3, 2016 1:09:20 PM by Hibernate Tools 4.3.1



/**
 * Loaichuyenbay generated by hbm2java
 */
public class Loaichuyenbay  implements java.io.Serializable {


     private Integer idloaichuyenbay;
     private String loaiChuyenBay;
     private String moTa;

    public Loaichuyenbay() {
    }

	
    public Loaichuyenbay(String loaiChuyenBay) {
        this.loaiChuyenBay = loaiChuyenBay;
    }
    public Loaichuyenbay(String loaiChuyenBay, String moTa) {
       this.loaiChuyenBay = loaiChuyenBay;
       this.moTa = moTa;
    }
   
    public Integer getIdloaichuyenbay() {
        return this.idloaichuyenbay;
    }
    
    public void setIdloaichuyenbay(Integer idloaichuyenbay) {
        this.idloaichuyenbay = idloaichuyenbay;
    }
    public String getLoaiChuyenBay() {
        return this.loaiChuyenBay;
    }
    
    public void setLoaiChuyenBay(String loaiChuyenBay) {
        this.loaiChuyenBay = loaiChuyenBay;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }




}


