package com.javaweb.model;
// Generated Dec 24, 2016 8:59:52 AM by Hibernate Tools 4.3.1



/**
 * Loaitintuc generated by hbm2java
 */
public class Loaitintuc  implements java.io.Serializable {


     private int idLoaiTin;
     private String loaiTin;
     private String moTa;

    public Loaitintuc() {
    }

	
    public Loaitintuc(int idLoaiTin, String loaiTin) {
        this.idLoaiTin = idLoaiTin;
        this.loaiTin = loaiTin;
    }
    public Loaitintuc(int idLoaiTin, String loaiTin, String moTa) {
       this.idLoaiTin = idLoaiTin;
       this.loaiTin = loaiTin;
       this.moTa = moTa;
    }
   
    public int getIdLoaiTin() {
        return this.idLoaiTin;
    }
    
    public void setIdLoaiTin(int idLoaiTin) {
        this.idLoaiTin = idLoaiTin;
    }
    public String getLoaiTin() {
        return this.loaiTin;
    }
    
    public void setLoaiTin(String loaiTin) {
        this.loaiTin = loaiTin;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }




}


