package com.javaweb.model;
// Generated Dec 20, 2016 11:01:57 PM by Hibernate Tools 4.3.1



/**
 * Phanhoi generated by hbm2java
 */
public class Phanhoi  implements java.io.Serializable {


     private Integer idphanhoi;
     private Integer idtaikhoan;
     private String fullName;
     private String email;
     private String phanHoi;

    public Phanhoi() {
    }

	
    public Phanhoi(String fullName, String email, String phanHoi) {
        this.fullName = fullName;
        this.email = email;
        this.phanHoi = phanHoi;
    }
    public Phanhoi(Integer idtaikhoan, String fullName, String email, String phanHoi) {
       this.idtaikhoan = idtaikhoan;
       this.fullName = fullName;
       this.email = email;
       this.phanHoi = phanHoi;
    }
   
    public Integer getIdphanhoi() {
        return this.idphanhoi;
    }
    
    public void setIdphanhoi(Integer idphanhoi) {
        this.idphanhoi = idphanhoi;
    }
    public Integer getIdtaikhoan() {
        return this.idtaikhoan;
    }
    
    public void setIdtaikhoan(Integer idtaikhoan) {
        this.idtaikhoan = idtaikhoan;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhanHoi() {
        return this.phanHoi;
    }
    
    public void setPhanHoi(String phanHoi) {
        this.phanHoi = phanHoi;
    }




}


