package com.javaweb.model;
// Generated Dec 12, 2016 2:00:47 PM by Hibernate Tools 4.3.1



/**
 * Taikhoan generated by hbm2java
 */
public class Taikhoan  implements java.io.Serializable {


     private Integer idTaiKhoan;
     private int idnguoidung;
     private String tenDangNhap;
     private String email;
     private String matKhau;
     private int idLoaiTk;

    public Taikhoan() {
    }

	
    public Taikhoan(int idnguoidung, String tenDangNhap, String matKhau, int idLoaiTk) {
        this.idnguoidung = idnguoidung;
        this.tenDangNhap = tenDangNhap;
        this.matKhau = matKhau;
        this.idLoaiTk = idLoaiTk;
    }
    public Taikhoan(int idnguoidung, String tenDangNhap, String email, String matKhau, int idLoaiTk) {
       this.idnguoidung = idnguoidung;
       this.tenDangNhap = tenDangNhap;
       this.email = email;
       this.matKhau = matKhau;
       this.idLoaiTk = idLoaiTk;
    }
   
    public Integer getIdTaiKhoan() {
        return this.idTaiKhoan;
    }
    
    public void setIdTaiKhoan(Integer idTaiKhoan) {
        this.idTaiKhoan = idTaiKhoan;
    }
    public int getIdnguoidung() {
        return this.idnguoidung;
    }
    
    public void setIdnguoidung(int idnguoidung) {
        this.idnguoidung = idnguoidung;
    }
    public String getTenDangNhap() {
        return this.tenDangNhap;
    }
    
    public void setTenDangNhap(String tenDangNhap) {
        this.tenDangNhap = tenDangNhap;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public int getIdLoaiTk() {
        return this.idLoaiTk;
    }
    
    public void setIdLoaiTk(int idLoaiTk) {
        this.idLoaiTk = idLoaiTk;
    }




}


