package com.javaweb.model;
// Generated Dec 12, 2016 2:00:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tintuc generated by hbm2java
 */
public class Tintuc  implements java.io.Serializable {


     private Integer idtintuc;
     private int idTaiKhoan;
     private String imgLink;
     private String imgList;
     private String tieuDe;
     private String noiDung;
     private Date ngayDang;
     private String ghiChu;

    public Tintuc() {
    }

	
    public Tintuc(int idTaiKhoan, String imgLink, String tieuDe, String noiDung) {
        this.idTaiKhoan = idTaiKhoan;
        this.imgLink = imgLink;
        this.tieuDe = tieuDe;
        this.noiDung = noiDung;
    }
    public Tintuc(int idTaiKhoan, String imgLink, String imgList, String tieuDe, String noiDung, Date ngayDang, String ghiChu) {
       this.idTaiKhoan = idTaiKhoan;
       this.imgLink = imgLink;
       this.imgList = imgList;
       this.tieuDe = tieuDe;
       this.noiDung = noiDung;
       this.ngayDang = ngayDang;
       this.ghiChu = ghiChu;
    }
   
    public Integer getIdtintuc() {
        return this.idtintuc;
    }
    
    public void setIdtintuc(Integer idtintuc) {
        this.idtintuc = idtintuc;
    }
    public int getIdTaiKhoan() {
        return this.idTaiKhoan;
    }
    
    public void setIdTaiKhoan(int idTaiKhoan) {
        this.idTaiKhoan = idTaiKhoan;
    }
    public String getImgLink() {
        return this.imgLink;
    }
    
    public void setImgLink(String imgLink) {
        this.imgLink = imgLink;
    }
    public String getImgList() {
        return this.imgList;
    }
    
    public void setImgList(String imgList) {
        this.imgList = imgList;
    }
    public String getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(String tieuDe) {
        this.tieuDe = tieuDe;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public Date getNgayDang() {
        return this.ngayDang;
    }
    
    public void setNgayDang(Date ngayDang) {
        this.ngayDang = ngayDang;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }




}


