package com.javaweb.model;
// Generated Dec 3, 2016 1:09:20 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ve generated by hbm2java
 */
public class Ve  implements java.io.Serializable {


     private Integer idve;
     private String ho;
     private String tenDem;
     private String ten;
     private Date ngaySinh;
     private String diaChi;
     private String sdt;
     private String soCmnd;
     private String quocTich;
     private int idchuyenbay;
     private int idloaive;
     private Integer idtaikhoan;

    public Ve() {
    }

	
    public Ve(String ho, String tenDem, String ten, String sdt, String soCmnd, String quocTich, int idchuyenbay, int idloaive) {
        this.ho = ho;
        this.tenDem = tenDem;
        this.ten = ten;
        this.sdt = sdt;
        this.soCmnd = soCmnd;
        this.quocTich = quocTich;
        this.idchuyenbay = idchuyenbay;
        this.idloaive = idloaive;
    }
    public Ve(String ho, String tenDem, String ten, Date ngaySinh, String diaChi, String sdt, String soCmnd, String quocTich, int idchuyenbay, int idloaive, Integer idtaikhoan) {
       this.ho = ho;
       this.tenDem = tenDem;
       this.ten = ten;
       this.ngaySinh = ngaySinh;
       this.diaChi = diaChi;
       this.sdt = sdt;
       this.soCmnd = soCmnd;
       this.quocTich = quocTich;
       this.idchuyenbay = idchuyenbay;
       this.idloaive = idloaive;
       this.idtaikhoan = idtaikhoan;
    }
   
    public Integer getIdve() {
        return this.idve;
    }
    
    public void setIdve(Integer idve) {
        this.idve = idve;
    }
    public String getHo() {
        return this.ho;
    }
    
    public void setHo(String ho) {
        this.ho = ho;
    }
    public String getTenDem() {
        return this.tenDem;
    }
    
    public void setTenDem(String tenDem) {
        this.tenDem = tenDem;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public String getSoCmnd() {
        return this.soCmnd;
    }
    
    public void setSoCmnd(String soCmnd) {
        this.soCmnd = soCmnd;
    }
    public String getQuocTich() {
        return this.quocTich;
    }
    
    public void setQuocTich(String quocTich) {
        this.quocTich = quocTich;
    }
    public int getIdchuyenbay() {
        return this.idchuyenbay;
    }
    
    public void setIdchuyenbay(int idchuyenbay) {
        this.idchuyenbay = idchuyenbay;
    }
    public int getIdloaive() {
        return this.idloaive;
    }
    
    public void setIdloaive(int idloaive) {
        this.idloaive = idloaive;
    }
    public Integer getIdtaikhoan() {
        return this.idtaikhoan;
    }
    
    public void setIdtaikhoan(Integer idtaikhoan) {
        this.idtaikhoan = idtaikhoan;
    }




}


